version: '3.8'

services:
  python-faq-chatbot:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - TOKENIZERS_PARALLELISM=false
    network_mode: "host"  # Add this line
